### ISSUE TITLE
Undefined function error in form.php

### ISSUE THREAD

**Issue by samkarpluk** [trepmal/mini-loops#8]
We are getting errors thrown from mini-loops in our widgets area:

` PHP Fatal error:  Uncaught Error: Call to undefined function get_available_post_statuses() in /srv/www/wordpress/wp-content/plugins/mini-loops/form.php:68
 Stack trace:
 #0 /srv/www/wordpress/wp-content/plugins/mini-loops/widget.php(78): include()
 #1 /srv/www/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(545): miniloops->form(Array)
 #2 /srv/www/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(485): WP_REST_Widget_Types_Controller->get_widget_form(Object(miniloops), Array)
 #3 /srv/www/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1140): WP_REST_Widget_Types_Controller->encode_form_data(Object(WP_REST_Request))
 #4 /srv/www/wordpress/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/widget-t...', Array, NULL)
 #5 /srv/www/wordpress/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dis in /srv/www/wordpress/wp-content/plugins/mini-loops/form.php on line 68`

Error goes away if I add a `require_once( ABSPATH . 'wp-admin/includes/post.php );` in form.php.

**Comment by trepmal** [comment]
Sorry I missed this nearly 1 year old issue :(

I've a pending fix in #10 which I hope to merge in soon.
